<?php
function prime_numbers_theme ($existing, $type, $theme, $path) {

    return [
        'prime_detect' => [
            'variables' => ['items' => [], 'user' => '', 'header'=>''],
        ]
    ];
}

function prime_numbers_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

    if ($form_id == 'primes_form') {
        $form['#attached']['library'][] = 'prime_numbers/simple_math';
    }
}